config/routes.rb
Rails.application.routes.draw do

   root 'users#index' 
    get "profile" => "users#show"
    get "/users/sign_in" => "sessions#new"
    post "users/sign_in" => "users#show"

   resources :users do
    resources :sessions
    resources :posts
  end
  

   resources :comments

  

end

app/models/add_column_to_post.rb
class AddColumnToPost < ActiveRecord::Base
end

app/models/add_post_id_to_comment.rb
class AddPostIdToComment < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :session
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 include ApplicationHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(user_params)
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

  end

  def show
  end

  def destroy
    @comment = Comment.find(params[:id])
     if@comment.destroy
      flash[:notice] = "Comment successfully deleted"
    else
      flash[:notice] = "Error"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @post = Post.order(id: :desc)

  end

 def new
    unless current_user
      flash[:alert] = "you must log in to create a post"
      redirect_to(:back)
    else
      @post = Post.new
    end
  end

 

    def create
      
      @post = current_user.posts.create post_params
       redirect_to user_post_path(params[:user_id], @post)
      
   end 

    


  def edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update
      flash[:notice] = "Post successfully updated."
    else
      flash[:notice] = " Post has an error."
  end
  redirect_to :back
end
  def show
    @post = Post.find(params[:id], @post)
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post Successfully deleted."
    else
      flash[:notice] = " There was a problem deleting the post."
  end
 redirect_to :back
end


private
  def post_params
  params.require(:post).permit(:content, :title)
  end
 end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


def new
  @user = User.new
end


  def create
  #create the user
    username = params[:username]
    password = params[:password]

 #find the user
  @user = User.where(username: username).first

  if @user.nil?
    flash[:alert] = "Not a user"
    redirect_to :back

    #if password and username are correct then a new session will be made
  else
     if @user.password == password
      session[:user_id] = @user.id
      flash[:alert] = "Welcome"
      redirect_to user_path(@user)
    end 
  end
 end


  def destroy
    session[:user_id] = nil
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  
    def show
   if params[:id]
     @user = User.find(params[:id])
    else
     redirect_to users_path unless current_user.present?
     @user = current_user
   end
 end


    

 

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User successfully created"
      redirect_to user_path(@user)
     else
      flash[:notice] = "User cannot be create."
       redirect_to :back    
     end
  end

  def edit
  end

  def update
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "user successfully deleted"
    else
      flash[:notice] = "Error occured while deleting. User could Not be deleted."
  
   redirect_to :back
   end
 end 
end

private

def user_params
  params.require(:user).permit(:fname, :lname, :email, :password, :username)
end

app/helpers/application_helper.rb
module ApplicationHelper
	# defining current user in session
  def current_user
    if session[:user_id]
      @current_user = User.find session[:user_id]
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Express Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" 
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" 
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="custom.scss">
</head>
<body>
 

<div class="wrapper">
 <div class="header">
 <h1>
 	Baby Chat!
 </h1>
 






<%= yield %>
</div>
</body>
</html>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<% @post.each do |post| %>
<p>
	<%=post.content %>

</p>
<% if post.user %>
 Written by: 
  <%=post.user.username %>
<% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, :url => {:action => "create"} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<p>
	<%= @post.content %>

</p>

<%= link_to 'Back', root_path %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title> Welcome To Express</title>
</head>
<body>
<button type="button"> 
<%=link_to('Sign In Here!', users_sign_in_path) %>
</button>
<button type="button">
<%=link_to('Register to Express Here!', new_user_path) %></button>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%=f.label "first name" %>
<%=f.text_field :fname %>
<%= f.label "last name" %>
<%= f.text_field :lname %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :username %>
<%= f.text_field :username %>
<%= f.label :password %>
<%= f.password_field :password %>


<%= f.submit %>

<% end %>

app/views/users/show.html.erb
<div class="user_welcome_page">

<h1>Hello <%= @user.fname %></h1> 


</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
 <strong>Posts associated with this user:</strong><br><br>
 <% @user.posts.each do |post| %>
 <%= post.content %><br>

 <% end %>
</p>
<%= link_to 'Create new posts', new_user_post_path(@user) %>
<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>